import"./assets/styles-DxcMbWHA.js";import{i as $,a as E}from"./assets/vendor-CG2pNq4b.js";const a=12;let y=1;const u={homeProducts:document.querySelector('.products[data-page="home"]'),homeCategories:document.querySelector(".categories"),notFoundDiv:document.querySelector(".not-found"),form:document.querySelector(".search-form"),modalProduct:document.querySelector(".modal-product"),modal:document.querySelector(".modal"),loadMoreBtn:document.querySelector(".load-more-btn")},{loadMoreBtn:P,homeProducts:A}=u;async function m(t){const{data:o}=await E.get(t);return o}function n(t){$.error({message:t,position:"bottomRight",backgroundColor:"#ef4040",messageColor:"#ffffff",maxWidth:"400"})}function w(t){t.innerHTML=""}function q(t,o){const e=t.querySelector(".categories__btn--active");e&&e.classList.remove("categories__btn--active"),o.classList.add("categories__btn--active")}function b(t){$.info({message:t,position:"bottomCenter",maxWidth:"400"})}function R(){const e=document.querySelector(".products__item").getBoundingClientRect().height;window.scrollBy({top:e*1.5,behavior:"smooth"})}function j(t){return t.map(o=>`<li>${o}</li>`).join("")}function I(){P.hidden=!1}function C(){P.hidden=!0}function p(t,o){console.log(`Current page: ${o}, Total: ${t}`),o*12>=t?(b("There are no more products to load at the moment."),C(),console.log("No more products to load. Button hidden.")):(I(),console.log("More products available. Button shown."))}function h(t){A.insertAdjacentHTML("beforeend",H(t))}async function g(t=1){const o=(t-1)*a,e=`https://dummyjson.com/products?limit=${a}&skip=${o}`;return m(e)}async function T(){return m("https://dummyjson.com/products/category-list")}async function L(t,o=1){const e="https://dummyjson.com/products/category/",c=(o-1)*a,s=`${e}${t}?limit=${a}&skip=${c}`;return m(s)}async function B(t,o=1){const e="https://dummyjson.com/products/search",c=(o-1)*a,s=`${e}?q=${t}&limit=${a}&skip=${c}`;return m(s)}async function U(t){const e=`https://dummyjson.com/products/${t}`;return m(e)}const{homeCategories:x,homeProducts:at,modalProduct:D}=u;function H(t){return t.map(({id:o,title:e,brand:c,category:s,price:i,thumbnail:f})=>`
  <li class="products__item" data-id="${o}">
    <img class="products__image" src="${f}" alt="${e}"/>
    <p class="products__title">${e}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:</span>${c}</p>
    <p class="products__category">Category: ${s}</p>
    <p class="products__price">Price: $${i}</p>
 </li>`).join("")}async function S(){try{const{products:t,total:o}=await g(y);h(t),p(o,y)}catch(t){console.error("Error while fetching products:",t),n("Something went wrong while loading products. Please try again later.")}}function O(t){return t.map(o=>`
    <li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>`).join("")}async function F(){try{const o=["All",...await T()];x.innerHTML=O(o)}catch{n("Something went wrong while loading categories. Please try again later.")}}function N(t){const{title:o,description:e,price:c,tags:s,images:i,shippingInformation:f,returnPolicy:k}=t;return`<img class="modal-product__img" src="${(i==null?void 0:i[0])||""}" alt="${o}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${o}</p>
        <ul class="modal-product__tags">${j(s)}</ul>
        <p class="modal-product__description">${e}</p>
        <p class="modal-product__shipping-information">Shipping: ${f}</p>
        <p class="modal-product__return-policy">Return Policy: ${k}</p>
        <p class="modal-product__price">Price: $${c}</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`}async function W(t){try{const o=await U(t);D.innerHTML=N(o)}catch{n("Failed to load product information. Please try again later.")}}const{modal:v}=u;function z(){v.classList.add("modal--is-open")}function V(){v.classList.remove("modal--is-open")}function G(t){const o=t.target.closest(".products__item");if(!o)return;const e=Number(o.dataset.id);e&&(W(e),z())}const{homeCategories:J,homeProducts:M,notFoundDiv:K,form:_}=u;let l="",r=1,d="";async function Q(t){if(t.target.classList.contains("categories__btn")){d=t.target.textContent.trim(),q(J,t.target),r=1,w(M);try{let o;d==="All"?o=await g(r):o=await L(d,r);const{products:e,total:c}=o;e.length===0?K.classList.add("not-found--visible"):(h(e),p(c,r))}catch(o){console.error("Oops! Couldn't fetch products:",o),n("Oops! Couldn't fetch products. Check your connection or try again.")}}}async function X(t){if(t.preventDefault(),r=1,w(M),l=_.elements.searchValue.value.trim(),!l){n("Please fill in the search field!");return}try{const{products:o,total:e}=await B(l,r);if(o.length===0){S(),n("Unfortunately, no results were found for this query.");return}h(o),p(e,r)}catch(o){console.error("An error occurred while searching for products:",o),n("An error occurred while searching for products. Please try again later.")}finally{_.reset()}}function Y(t){const o=t.target.closest(".modal__close-btn");t.target.closest(".modal-product__btn--cart"),o&&V()}async function Z(t){r++,C();try{let o;l?o=await B(l,r):d?o=await L(d,r):o=await g(r);const{products:e,total:c}=o;e.length===0?b("No products found matching your search criteria."):(h(e),setTimeout(()=>R()),p(c,r))}catch{n("Oops! Something went wrong. Please try again later.")}}const{homeCategories:tt,form:ot,homeProducts:et,modal:rt,loadMoreBtn:ct}=u;S();F();tt.addEventListener("click",Q);ot.addEventListener("submit",X);et.addEventListener("click",G);rt.addEventListener("click",Y);ct.addEventListener("click",Z);
//# sourceMappingURL=index.js.map
